#serverless.yml
service: serverless-flask-container

provider:
  name: aws
  region: ${opt:region, 'eu-west-1'}
  ecr:
    images:
      appimage:
        path: ./
  layers:
    - arn:aws:lambda:eu-west-1:113088814899:layer:Klayers-python37-Pillow:11

functions:
  main:
    image:
      name: appimage
    timeout: 30
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'
